<script setup lang="ts">

</script>

<template>
  <div>
    <h1 class="q-my-xl">Datenschutz</h1>
    <p>magnus es, domine, et laudabilis valde. magna virtus tua et sapientiae tuae non est numerus. et laudare te vult homo, aliqua portio creaturae tuae, et homo circumferens mortalitatem suam, circumferens testimonium peccati sui et testimonium quia superbis resistis; et tamen laudare te vult homo, aliqua portio creaturae tuae. tu excitas ut laudare te delectet, quia fecisti nos ad te et inquietum est cor nostrum donec requiescat in te. da mihi, domine, scire et intellegere utrum sit prius invocare te an laudare te, et scire te prius sit an invocare te. sed quis te invocat nesciens te? aliud enim pro alio potest invocare nesciens. an potius invocaris ut sciaris? quomodo autem invocabunt, in quem non crediderunt? aut quomodo credent sine praedicante? et laudabunt dominum qui requirunt eum: quaerentes enim inveniunt eum et invenientes laudabunt eum. quaeram te, domine, invocans te et invocem te credens in te: praedicatus enim es nobis. invocat te, domine, fides mea, quam dedisti mihi, quam inspirasti mihi per humanitatem filii tui, per ministerium praedicatoris tui.</p>
    <p>et quomodo invocabo deum meum, deum et dominum meum, quoniam utique in me ipsum eum vocabo, cum invocabo eum? et quis locus est in me quo veniat in me deus meus, quo deus veniat in me, deus qui fecit caelum et terram? itane, domine deus meus? est quicquam in me quod capiat te? an vero caelum et terra, quae fecisti et in quibus me fecisti, capiunt te? an quia sine te non esset quidquid est, fit ut quidquid est capiat te? quoniam itaque et ego sum, quid peto ut venias in me, qui non essem nisi esses in me? non enim ego iam inferi, et tamen etiam ibi es, nam etsi descendero in infernum, ades. non ergo essem, deus meus, non omnino essem, nisi esses in me. an potius non essem nisi essem in te, ex quo omnia, per quem omnia, in quo omnia? etiam sic, domine, etiam sic. quo te invoco, cum in te sim? aut unde venias in me? quo enim recedam extra caelum et terram, ut inde in me veniat deus meus, qui dixit, 'caelum et terram ego impleo'? </p>
    <p>capiunt ergone te caelum et terra, quoniam tu imples ea? an imples et restat, quoniam non te capiunt? et quo refundis quidquid impleto caelo et terra restat ex te? an non opus habes ut quoquam continearis, qui contines omnia, quoniam quae imples continendo imples? non enim vasa quae te plena sunt stabilem te faciunt, quia etsi frangantur non effunderis. et cum effunderis super nos, non tu iaces sed erigis nos, nec tu dissiparis sed conligis nos. sed quae imples omnia, te toto imples omnia. an quia non possunt te totum capere omnia, partem tui capiunt et eandem partem simul omnia capiunt? an singulas singula et maiores maiora, minores minora capiunt? ergo est aliqua pars tua maior, aliqua minor? an ubique totus es et res nulla te totum capit?</p>
    <p>quid es ergo, deus meus? quid, rogo, nisi dominus deus? quis enim dominus praeter dominum? aut quis deus praeter deum nostrum? summe, optime, potentissime, omnipotentissime, misericordissime et iustissime, secretissime et praesentissime, pulcherrime et fortissime, stabilis et incomprehensibilis, immutabilis mutans omnia, numquam novus numquam vetus, innovans omnia et in vetustatem perducens superbos et nesciunt. semper agens semper quietus, conligens et non egens, portans et implens et protegens, creans et nutriens et perficiens, quaerens cum nihil desit tibi. amas nec aestuas, zelas et securus es, paenitet te et non doles, irasceris et tranquillus es, opera mutas nec mutas consilium, recipis quod invenis et numquam amisisti. numquam inops et gaudes lucris, numquam avarus et usuras exigis, supererogatur tibi ut debeas: et quis habet quicquam non tuum? reddis debita nulli debens, donas debita nihil perdens. et quid diximus, deus meus, vita mea, dulcedo mea sancta, aut quid dicit aliquis cum de te dicit? et vae tacentibus de te, quoniam loquaces muti sunt.</p>
  </div>
</template>

<style scoped>

</style>
