# Generated by Django 5.2.7 on 2026-05-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba3_nk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempresultmodel',
            name='code',
            field=models.CharField(default='xxx', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tempresultmodel',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
